name: ci-test
on: [push]
jobs:
  test-env-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: show env variables
        run: |
	  echo Local repo URL : $(git config --get remote.origin.url)
          echo GitHub Actions repo URL  : $GITHUB_REPOSITORY
          echo Branc name : $GITHUB_REF_NAME
          echo commit SHA : $GITHUB_SHA
          echo commit short SHA : ${GITHUB_SHA::7}
          echo PR number : ${{ github.event.number }}
